
CREATE TABLE ACC_CHART(
    CHART_NO  NUMBER  NOT NULL
   ,CHART_NAME  VARCHAR2(500)  
   ,NATURE_TYP  VARCHAR2(1) )
   / 
CREATE TABLE ACC_VOUCHER_DTL(
    VOUCHER_DTL_NO  NUMBER  NOT NULL
   ,VOUCHER_NO  NUMBER  
   ,LEDGER_NO  NUMBER  
   ,SUBLEDGER_NO  NUMBER  
   ,AMOUNT  NUMBER  
   ,REMARKS  VARCHAR2(200)  
   ,DR_AMT  NUMBER  
   ,CR_AMT  NUMBER  )
   /
CREATE TABLE ACC_VOUCHER_MST(
    VOUCHER_NO  NUMBER  NOT NULL
   ,VOUCHER_DATE  DATE  
   ,REMARKS  VARCHAR2(200)  
   ,VOUCHER_ID  VARCHAR2(10)  
   ,VOUCHERTYPE_NO  NUMBER  
   ,TOTAL_AMT  NUMBER  )
   /
CREATE TABLE AC_BANK(
    BANK_NO  NUMBER(30,0)  
   ,BANK_NAME  VARCHAR2(100)  NOT NULL)
   /
CREATE TABLE AC_VOUCHERTYPE(
    VOUCHERTYPE_NO  NUMBER  
   ,VOUCHERTYPE_NAME  VARCHAR2(30)  
   ,ALIAS  VARCHAR2(3)  
   ,VOUCHER_TYPE  VARCHAR2(3)  
   ,DESCRIPTION  VARCHAR2(100)  
   ,DEFAULT_STAT  NUMBER(1,0)  
   ,SS_CREATOR  NUMBER(10,0)  
   ,SS_CREATED_ON  DATE  
   ,SS_MODIFIER  NUMBER(10,0)  
   ,SS_MODIFIED_ON  DATE  )
   /
CREATE TABLE FA_ASSET_REGISTER(
    ASSET_NO  NUMBER  
   ,ASSET_ID  VARCHAR2(100)  
   ,ASSET_NAME  VARCHAR2(200)  
   ,ASSET_DESCRIPTION  VARCHAR2(500)  
   ,ASSET_GRP_NO  NUMBER  
   ,SERIAL_NO  VARCHAR2(100)  
   ,BARCODE  VARCHAR2(100)  
   ,BRAND  VARCHAR2(100)  
   ,COLOR  VARCHAR2(100)  
   ,WARRENTY_DATE  DATE  
   ,DEPARMENT_NO  NUMBER  
   ,SECTION_NO  NUMBER  
   ,COMPANY_NO  NUMBER  
   ,ASSET_LOCATION  VARCHAR2(100)  
   ,ASSET_AREA  VARCHAR2(100)  
   ,LINE  VARCHAR2(100)  
   ,ROOM  VARCHAR2(100)  
   ,PURCHASE_DATE  DATE  
   ,WARRANTY_DATE  DATE  
   ,SUPPLIER_NO  NUMBER  
   ,PURCHASE_COST  NUMBER  
   ,INSTALLATION_COST  NUMBER  
   ,ASSET_LIFE  NUMBER  
   ,DEPRICIATION_AMOUNT  NUMBER  
   ,SALVAGE_VALUE  NUMBER  
   ,ASSIGNED_TO_PERSON_NO  NUMBER  
   ,ASSIGNED_PERSON  VARCHAR2(100)  
   ,ACTIVE_STATUS  NUMBER  
   ,CONDITION  VARCHAR2(100)  
   ,ITEM_NO  NUMBER  
   ,SS_CREATOR  NUMBER(10,0)  
   ,SS_CREATED_ON  DATE  
   ,SS_MODIFIER  NUMBER(10,0)  
   ,SS_MODIFIED_ON  DATE  
   ,RATE  NUMBER(12,2)  
   ,CONVERION_RATE  NUMBER(12,2)  
   ,AMOUNT  NUMBER(12,2)  
   ,ORIGIN_NO  NUMBER(10,0)  
   ,LC_NO  NUMBER(10,0)  
   ,OWNER  VARCHAR2(100)  
   ,DEED_NO  VARCHAR2(100)  
   ,DEED_DATE  DATE  
   ,MORTGAGE_WITH  VARCHAR2(100)  
   ,MORTGAGE_NO  VARCHAR2(100)  
   ,SUPPLIER  VARCHAR2(500)  
   ,CAPACITY  VARCHAR2(100)  
   ,QTY  NUMBER(10,0)  
   ,UNIT_NO  NUMBER(10,0)  
   ,REMARKS  VARCHAR2(200)  
   ,ASSET_TYPENO  NUMBER  
   ,MAC_ID  VARCHAR2(100)  
   ,BRAND_NO  NUMBER  
   ,DEVICE_NO  NUMBER  
   ,ASSET_LOCATION_NO  NUMBER  
   ,ADDESS_OF_REGISTRY_OFFICE  VARCHAR2(200)  
   ,MOUZA  VARCHAR2(200)  
   ,UNION_  VARCHAR2(200)  
   ,THANA  VARCHAR2(200)  
   ,TYPES_OF_LAND  VARCHAR2(200)  
   ,DISTRICT  VARCHAR2(200)  
   ,JL_NO  VARCHAR2(200)  
   ,KHAITIAN_NO  VARCHAR2(200)  
   ,DAG_NO  VARCHAR2(200)  
   ,MORTGAGE_DATE  DATE  
   ,TYPE_OF_DOLIL  VARCHAR2(200)  )
   /
CREATE TABLE HR_EMP(
    EMP_NO  NUMBER(30,0)  
   ,EMP_ID  VARCHAR2(50)  
   ,USER_NAME  VARCHAR2(30)  
   ,PWD  VARCHAR2(40)  
   ,BU_NO  NUMBER(30,0)  
   ,JOBTITLE_NO  NUMBER(30,0)  
   ,SALUTATION  VARCHAR2(20)  
   ,FNAME  VARCHAR2(50)  
   ,LNAME  VARCHAR2(20)  
   ,ACTIVE_STAT  NUMBER  
   ,COMPANY_NO  NUMBER  )
   /
CREATE TABLE HTMLDB_PLAN_TABLE(
    STATEMENT_ID  VARCHAR2(30)  
   ,PLAN_ID  NUMBER  
   ,TIMESTAMP  DATE  
   ,REMARKS  VARCHAR2(4000)  
   ,OPERATION  VARCHAR2(30)  
   ,OPTIONS  VARCHAR2(255)  
   ,OBJECT_NODE  VARCHAR2(128)  
   ,OBJECT_OWNER  VARCHAR2(128)  
   ,OBJECT_NAME  VARCHAR2(128)  
   ,OBJECT_ALIAS  VARCHAR2(261)  
   ,OBJECT_INSTANCE  NUMBER  
   ,OBJECT_TYPE  VARCHAR2(128)  
   ,OPTIMIZER  VARCHAR2(255)  
   ,SEARCH_COLUMNS  NUMBER  
   ,ID  NUMBER  
   ,PARENT_ID  NUMBER  
   ,DEPTH  NUMBER  
   ,POSITION  NUMBER  
   ,COST  NUMBER  
   ,CARDINALITY  NUMBER  
   ,BYTES  NUMBER  
   ,OTHER_TAG  VARCHAR2(255)  
   ,PARTITION_START  VARCHAR2(255)  
   ,PARTITION_STOP  VARCHAR2(255)  
   ,PARTITION_ID  NUMBER  
   ,OTHER  LONG  
   ,DISTRIBUTION  VARCHAR2(30)  
   ,CPU_COST  NUMBER  
   ,IO_COST  NUMBER  
   ,TEMP_SPACE  NUMBER  
   ,ACCESS_PREDICATES  VARCHAR2(4000)  
   ,FILTER_PREDICATES  VARCHAR2(4000)  
   ,PROJECTION  VARCHAR2(4000)  
   ,TIME  NUMBER  
   ,QBLOCK_NAME  VARCHAR2(128)  )
   /
CREATE TABLE SA_COMPANY(
    COMPANY_NO  NUMBER  
   ,COMPANY_NAME  VARCHAR2(200)  
   ,ADDRESS  VARCHAR2(500)  
   ,CONTACT_NO  VARCHAR2(20)  )
   /
CREATE TABLE SA_CURRENCY(
    CUR_NO  NUMBER(8,0)  NOT NULL
   ,CUR_NAME  VARCHAR2(20)  
   ,CUR_ID  VARCHAR2(10)  
   ,SYMBOL  VARCHAR2(5)  
   ,ISO_CODE  VARCHAR2(2)  
   ,BASE_FLAG  NUMBER  
   ,SS_CREATOR  NUMBER(10,0)  
   ,SS_CREATED_ON  VARCHAR2(20)  
   ,SS_MODIFIER  NUMBER(10,0)  
   ,SS_MODIFIED_ON  VARCHAR2(20)  
   ,SS_OG_NO  NUMBER(10,0)  
   ,UNIT_NAME  VARCHAR2(50)  )
   /
CREATE TABLE SA_LOOKUP(
    LOOKUP_NO  NUMBER(30,0)  NOT NULL
   ,LOOKUP_NAME  VARCHAR2(100)  NOT NULL
   ,DESCR  VARCHAR2(500)  
   ,CAN_CHANGE  NUMBER(1,0)  
   ,SS_CREATOR  NUMBER(10,0)  
   ,SS_CREATED_ON  VARCHAR2(20)  
   ,SS_MODIFIER  NUMBER(10,0)  
   ,SS_MODIFIED_ON  VARCHAR2(20)  
   ,SS_OG_NO  NUMBER(10,0)  )
   /
CREATE TABLE SA_LOOKUPDTL(
    LOOKUP_NO  NUMBER(30,0)  NOT NULL
   ,DTL_NAME  VARCHAR2(100)  NOT NULL
   ,ACTIVE_STAT  NUMBER(1,0)  
   ,LOOKUPDTL_NO  NUMBER(30,0)  NOT NULL
   ,SS_CREATOR  NUMBER(10,0)  
   ,SS_CREATED_ON  VARCHAR2(20)  
   ,SS_MODIFIER  NUMBER(10,0)  
   ,SS_MODIFIED_ON  VARCHAR2(20)  
   ,DESCR  VARCHAR2(300)  
   ,SS_OG_NO  NUMBER(10,0)  )
   /
CREATE TABLE SA_ORG(
    ORG_NO  NUMBER  
   ,ORG_NAME  VARCHAR2(200)  
   ,ADDRESS  VARCHAR2(500)  
   ,CONTACT_NO  VARCHAR2(20)  )
   /
CREATE TABLE STU_ATTENDANCE(
    ATTN_ID  NUMBER  NOT NULL
   ,ATTN_DATE  DATE  
   ,STUDENT_NO  VARCHAR2(4000)  
   ,IS_PRESENT  VARCHAR2(4000)  )
   /
CREATE TABLE STU_CLASS(
    CLASS_NO  NUMBER  
   ,CLASS_ID  VARCHAR2(50)  
   ,CLASS_NAME  VARCHAR2(100)  
   ,ACTIVE_STATUS  NUMBER  )
   /
CREATE TABLE STU_CLASS_WISE_FEE(
    FEE_NO  NUMBER  
   ,FEE_NAME  VARCHAR2(200)  
   ,CHART_NO  NUMBER  
   ,SESSION_NO  NUMBER  
   ,CLASS_NO  NUMBER  
   ,AMOUNT  NUMBER  
   ,REMARKS  NUMBER  )
   /
CREATE TABLE STU_GUARDIAN(
    STUDENT_NO  NUMBER  
   ,FATHER_NAME  VARCHAR2(150)  
   ,FATHERS_QUALIFICATION  VARCHAR2(100)  
   ,FATHERS_OCCUPATION  VARCHAR2(100)  
   ,FATHERS_CONTACT_NO  VARCHAR2(50)  
   ,FATHERS_EMAIL  VARCHAR2(100)  
   ,MOTHER_NAME  VARCHAR2(150)  
   ,MOTHERS_OCCUPATION  VARCHAR2(100)  
   ,MOTHERS_QUALIFICATION  VARCHAR2(100)  
   ,MOTHERS_CONTACT_NO  VARCHAR2(50)  
   ,REMARKS  VARCHAR2(500)  
   ,RECEIVER_NAME  VARCHAR2(100)  
   ,RECEIVER_RELATION  VARCHAR2(100)  
   ,MAIN_GUARDIAN  VARCHAR2(50)  )
   /
CREATE TABLE STU_PAYMENT_DTL(
    PAYMENT_DTL_NO  NUMBER  NOT NULL
   ,PAYMENT_NO  NUMBER  
   ,LEDGER_NO  NUMBER  
   ,AMOUNT  NUMBER  
   ,STUDENT_NO  NUMBER  
   ,IS_PAID  NUMBER  
   ,SESSION_NO  NUMBER  
   ,CLASS_NO  NUMBER  )
   /
CREATE TABLE STU_PAYMENT_MST(
    PAYMENT_NO  NUMBER  NOT NULL
   ,PAYMENT_DATE  DATE  )
   /
CREATE TABLE STU_REG_SESSION(
    SESSION_NO  NUMBER  
   ,SESSION_ID  VARCHAR2(50)  
   ,SESSION_NAME  VARCHAR2(100)  
   ,SESSION_NAME_OTHERS  VARCHAR2(100)  
   ,ACTIVE_STATUS  NUMBER  
   ,SESSION_START_DT  DATE  
   ,SESSION_END_DT  DATE  )
   /
CREATE TABLE STU_RESULT(
    RESULT_NO  NUMBER  NOT NULL
   ,CLASS_NO  NUMBER  
   ,ACADEMIC_YEAR  NUMBER  )
   /
CREATE TABLE STU_RESULT_DTL(
    RESULT_NO  NUMBER  
   ,RESULT_DTL_NO  NUMBER  NOT NULL
   ,STUDENT_NO  NUMBER  
   ,COURSE_WORK  NUMBER  
   ,NARRATIVE  NUMBER  
   ,OBJECTIVE  NUMBER  
   ,PRACTICAL  NUMBER  )
   /
CREATE TABLE STU_RESULT_MST(
    RESULT_NO  NUMBER  NOT NULL
   ,RESULT_DATE  DATE  
   ,SESSION_NO  NUMBER  
   ,CLASS_NO  NUMBER  
   ,TERM_NO  NUMBER  
   ,SUBJECT_NO  NUMBER  )
   /
CREATE TABLE STU_STUDENT(
    STUDENT_NO  NUMBER  
   ,STUDENT_ID  VARCHAR2(20)  
   ,FIRST_NAME  VARCHAR2(150)  
   ,LAST_NAME  VARCHAR2(150)  
   ,DATE_OF_BIRTH  DATE  
   ,GENDER  VARCHAR2(20)  
   ,PRES_ADDRESS  VARCHAR2(200)  
   ,PERM_ADDRESS  VARCHAR2(150)  
   ,RELIGION  VARCHAR2(25)  
   ,NATIONALITY  VARCHAR2(25)  
   ,BLOOD_GROUP  VARCHAR2(10)  
   ,BIRTH_CERTIFICATE_NO  VARCHAR2(50)  
   ,DISABILITY  VARCHAR2(100)  
   ,ADMISSION_DATE  DATE  
   ,CLASS_NO  NUMBER  
   ,ROLL_NO  VARCHAR2(10)  
   ,CONTACT_MOBILE_NO  VARCHAR2(20)  
   ,IS_ACTIVE  NUMBER  
   ,REG_SESSION_NO  NUMBER  
   ,DATE_OF_BIRTH_  DATE  
   ,ADMISSION_DATE_  DATE  
   ,INSTITUTE_NO  NUMBER  )
   /
CREATE TABLE STU_SUBJECT(
    SUBJECT_NO  NUMBER  
   ,CLASS_NO  NUMBER  
   ,SUBJECT_ID  VARCHAR2(50)  
   ,SUBJECT_CODE  VARCHAR2(50)  
   ,SUBJECT_NAME  VARCHAR2(100)  
   ,MARKS  NUMBER  
   ,SYLLABUS  VARCHAR2(500)  
   ,REMARKS  VARCHAR2(100)  
   ,ACTIVE_STATUS  NUMBER)
   /  
CREATE TABLE STU_TEACHER(
    TEACHER_NO  NUMBER  
   ,TEACHER_ID  VARCHAR2(20)  
   ,FIRST_NAME  VARCHAR2(150)  
   ,LAST_NAME  VARCHAR2(150)  
   ,DATE_OF_BIRTH  DATE  
   ,GENDER  VARCHAR2(20)  
   ,PRES_ADDRESS  VARCHAR2(200)  
   ,PERM_ADDRESS  VARCHAR2(200)  
   ,RELIGION  VARCHAR2(25)  
   ,NATIONALITY  VARCHAR2(25)  
   ,BLOOD_GROUP  VARCHAR2(10)  
   ,BIRTH_CERTIFICATE_NO  VARCHAR2(50)  
   ,NATIONAL_ID  VARCHAR2(50)  
   ,DISABILITY  VARCHAR2(100)  
   ,JOINING_DATE  DATE  
   ,SALARY  NUMBER  
   ,IS_ACTIVE  NUMBER  
   ,CONTACT_MOBILE_NO  VARCHAR2(20)  )
   /


